#!/bin/bash

[[ $3 != "/" ]] && exit 0

/usr/bin/python /Library/Security/SecurityAgentPlugins/KeychainMinder.bundle/Contents/Resources/update_authdb.py --install

user=$(/usr/bin/stat -f '%u' /dev/console)
[[ -z "$user" ]] && exit 0
/bin/launchctl asuser ${user} /bin/launchctl load /Library/LaunchAgents/com.google.corp.keychainminder.plist
/bin/launchctl load /Library/LaunchDaemons/com.google.corp.keychainminderagent.plist

exit 0
